development:
  adapter: postgresql
  encoding: unicode
  database: fb_graph_friend_filter_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fb_graph_friend_filter_test
  pool: 5
  username:
  password:
